version: '3'
services:
  php:
    build:
      context: './php/'
      args:
        - PHP_VERSION=${PHP_VERSION:-7.3}
        - WITH_XDEBUG=${WITH_XDEBUG:-0}
        - GIT_USER=${GIT_USER}
        - GIT_EMAIL=${GIT_EMAIL}
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www/html/
    links:
      - db
    container_name: php
    env_file: .env

  php_classic:
    build:
      context: './php_classic/'
      args:
        - PHP_VERSION=${PHP_VERSION:-7.3}
        - WITH_XDEBUG=${WITH_XDEBUG:-0}
        - GIT_USER=${GIT_USER}
        - GIT_EMAIL=${GIT_EMAIL}
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www/html/
    links:
      - db
    container_name: php_classic
    env_file: .env

  apache:
    build:
      context: './apache/'
    depends_on:
      - php
    ports:
      - "8090:80"
    volumes:
      - ../:/var/www/html/
      - ./logs:/var/log/docker
      - ./sites-enabled:/usr/local/apache2/sites-enabled
    container_name: apache

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./mysql-data:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    expose:
      - 3306
    container_name: mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: adminer

volumes:
  data: